### ISSUE TITLE
Weitere FabLabs

### ISSUE THREAD

**Issue by mgmax** [fabrikationslabor/fabrikationslabor.github.io#11]
Via Google Alerts bin ich auf folgende Labs gestoßen, die noch nicht in der Liste sind:
- Neustadt a.d. Aisch / Bad Windsheim http://www.fablab-nea.de/
- Dortmund als Teil von DEZENTRALE https://dezentrale-dortmund.de/index.php/fablab/
- Zürich (ja, nicht mehr Deutschland, aber noch deutschsprachiger Raum) https://zurich.fablab.ch/

FabLabs, die nicht der Öffentlichkeit (sondern z.B. nur Uni-Angehörigen) zugänglich sind aber trotzdem so heißen, habe ich hier ausgespart; da sehe ich keinen Sinn dahinter das öffentlich zu dokumentieren.

**Comment by renebohne** [comment]
alle drei Labs wurden hinzugefügt.
