### ISSUE TITLE
noch mehr neue Labs

### ISSUE THREAD

**Issue by mgmax** [fabrikationslabor/fabrikationslabor.github.io#17]
Österreich:
- FH Kufstein, leider keine echte Webseite? https://www.fh-kufstein.ac.at/News/Fablab
- Mödling http://verein.handwerkstadt.org/ein-ort-zum-selbermachen/fablab-moedling/ 
- Innsbruck http://fablab.spielraumfueralle.at/

DE:
- "Ideenreich" FH Flensburg https://hs-flensburg.de/hochschule/organisation/einrichtungen/fablab-ideenreich

Italien/Südtirol:
- Uni Bozen (leider keine sinnvolle Webseite?, ohne Facebook-Login kann ich nicht sagen ob die überhaupt offen haben): https://www.facebook.com/pg/bitzunibzfablab/events/?ref=page_internal

**Comment by renebohne** [comment]
Flensburg und Innsbruck wurden hinzugefügt.
Bei den anderen ist nicht klar, ob sie verstanden haben, was ein FabLab ist. Sie haben u.a. die Fab Charter nicht online. 
Wir beobachten mal, ob sie noch echte Webseiten aufsetzen und ergänzen sie dann ggf. später.
